version: '3.8'

services:
  tasks-ui:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - API_BASE_URL=https://springboot-gcp-api-service-b02c0d80-1005440968570.us-central1.run.app/api
      - PORT=8080
      - VITE_APP_ENV=development
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge
