version: '3.8'

services:
  tasks-ui:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - API_BASE_URL=http://tasks-api:8080/api
      - PORT=8080
      - VITE_APP_ENV=development
    depends_on:
      - tasks-api
    networks:
      - tasks-network

  tasks-api:
    build: 
      context: ../springboot-gcp-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge
